title: "BRF BoKlok Ryttaren"
description: "Välkommen till BRF BoKlok Ryttaren!"
theme: jekyll-theme-cayman

url: "https://brf-boklok-ryttaren.github.io"
baseurl: ""

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
